// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    [Migration("20250822163559_HealthCareCategory_and_SubCategory_Seeding")]
    partial class HealthCareCategory_and_SubCategory_Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7145)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7151)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7154)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7157)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7160)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7162)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7165)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7167)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7170)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7172)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7175)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7177)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7179)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7182)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7184)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7187)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7189)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7191)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7193)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7196)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7198)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7201)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7203)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7205)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7208)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7213)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7215)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7218)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7220)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7222)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7225)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7227)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7229)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7232)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7234)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7236)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7704),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7711),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7715),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7718),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7720),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7723),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7725),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7729),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7732),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7735),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7737),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7740),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7742),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7745),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7748),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7750),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7753),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7755),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7758),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7761),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7763),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7766),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7768),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7771),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7774),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7776),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7779),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7781),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2025, 8, 22, 16, 35, 57, 997, DateTimeKind.Utc).AddTicks(7784),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
