// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    [Migration("20250830080956_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2817)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2824)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2826)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2828)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2830)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2831)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2833)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2835)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2836)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2838)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2840)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2841)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2843)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2844)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2845)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2846)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2848)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2849)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2851)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2852)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2854)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2856)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2857)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2859)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2860)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2861)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2863)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2864)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2866)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2867)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2868)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2870)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2871)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2872)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2874)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(2875)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3112),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3116),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3118),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3120),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3122),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3124),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3126),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3127),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3129),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3130),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3132),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3134),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3135),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3137),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3138),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3140),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3141),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3215),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3217),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3219),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3220),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3222),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3223),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3225),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3227),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3228),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3230),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3231),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2025, 8, 30, 8, 9, 55, 805, DateTimeKind.Utc).AddTicks(3233),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("GNW_Bazzar.Entity.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
