// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    [Migration("20250823102808_2")]
    partial class _2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6448)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6450)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6451)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6452)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6453)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6454)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6455)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6456)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6457)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6458)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6459)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6460)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6461)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6462)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6463)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6464)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6465)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6466)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6467)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6468)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6469)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6470)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6471)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6472)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6473)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6477)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6478)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6479)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6480)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6481)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6482)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6483)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6484)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6485)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6486)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6487)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6634),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6637),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6638),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6640),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6641),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6642),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6643),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6645),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6646),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6647),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6649),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6650),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6651),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6652),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6653),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6654),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6655),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6656),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6658),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6659),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6660),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6661),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6662),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6663),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6664),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6665),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6666),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6667),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2025, 8, 23, 10, 28, 7, 780, DateTimeKind.Utc).AddTicks(6668),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
