// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    [Migration("20260224113817_doctoratbleUpdated")]
    partial class doctoratbleUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryMasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Health Care",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3217),
                            Description = "Health Care related services",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Food",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3221),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Shopping",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3223),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Makeovers",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3224),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Events",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3226),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Travel",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3227),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Homecare",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3228),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Property",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3230),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Astrology",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3231),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Education",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3232),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "FitLife",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3304),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Pets",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3306),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Relocation",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3307),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Finance",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3308),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 15L,
                            CategoryName = "Security",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3310),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 16L,
                            CategoryName = "Service",
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3311),
                            Description = "",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CategoryMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AboutDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CategoryMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3518)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3521)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3523)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3524)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3525)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3527)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3528)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3530)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3531)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3532)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3534)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3535)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3536)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3537)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3539)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3541)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3542)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3543)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3545)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3546)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3547)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3548)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3549)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3551)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3554)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3558)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3560)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3561)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3563)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3564)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3565)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3567)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3568)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3573)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 24, 11, 38, 17, 27, DateTimeKind.Utc).AddTicks(3574)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Attempts")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Sponsor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Client", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.CategoryMaster", "CategoryMaster")
                        .WithMany()
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "healthCareCategory")
                        .WithMany()
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("healthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.CategoryMaster", "CategoryMaster")
                        .WithMany("HealthCareCategories")
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("Otp")
                        .HasForeignKey("GNW_Bazzar.Entity.Otp", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("GNW_Bazzar.Entity.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Navigation("HealthCareCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Navigation("Otp")
                        .IsRequired();

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
