// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    [Migration("20260210130834_SponsorAdded")]
    partial class SponsorAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryMasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Health Care",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4822),
                            Description = "Health Care related services",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Food",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4826),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Shopping",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4827),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Makeovers",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4828),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Events",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4830),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Travel",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4831),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Homecare",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4832),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Property",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4833),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Astrology",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4834),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Education",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4835),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "FitLife",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4836),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Pets",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4837),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Relocation",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4838),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Finance",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4840),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 15L,
                            CategoryName = "Security",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4841),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 16L,
                            CategoryName = "Service",
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(4842),
                            Description = "",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CategoryMasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AboutDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<long>("HealthCareSubCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareSubCategoryId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CategoryMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5003)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5006)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5007)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5008)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5009)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5011)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5012)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5013)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5014)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5015)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5016)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5017)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5018)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5019)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5021)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5022)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5025)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5026)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5027)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5028)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5029)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5030)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5031)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5032)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5033)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5034)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5035)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5036)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5037)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5038)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5039)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5040)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5041)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5045)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5046)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5046)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5152),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5154),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5155),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5156),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5158),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5159),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5160),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5161),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5162),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5163),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5164),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5165),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5166),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5167),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5168),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5169),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5170),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5171),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5172),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5173),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5174),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5175),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5176),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5177),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5178),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5179),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5180),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5181),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2026, 2, 10, 13, 8, 33, 438, DateTimeKind.Utc).AddTicks(5182),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Attempts")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Sponsor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Frequency")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Client", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.CategoryMaster", "CategoryMaster")
                        .WithMany()
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareSubCategory", "healthCareSubCategory")
                        .WithMany()
                        .HasForeignKey("HealthCareSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("healthCareSubCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.CategoryMaster", "CategoryMaster")
                        .WithMany("HealthCareCategories")
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("Otp")
                        .HasForeignKey("GNW_Bazzar.Entity.Otp", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("GNW_Bazzar.Entity.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Navigation("HealthCareCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Navigation("Otp")
                        .IsRequired();

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
