// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    partial class GNW_BazaarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5817)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5827)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5829)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5831)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5833)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5835)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5837)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5839)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5841)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5843)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5845)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5847)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5849)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5851)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5853)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5855)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5857)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5859)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5861)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5863)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5864)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5866)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5868)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5870)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5872)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5873)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5875)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5877)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5879)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5881)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5883)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5885)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5887)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5889)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5891)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(5920)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6327),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6332),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6335),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6337),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6339),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6341),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6343),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6345),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6347),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6350),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6352),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6355),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6357),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6359),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6361),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6363),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6365),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6367),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6369),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6371),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6373),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6376),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6378),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6380),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6382),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6384),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6386),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6388),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2025, 9, 2, 14, 57, 39, 92, DateTimeKind.Utc).AddTicks(6390),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Attempts")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("Otp")
                        .HasForeignKey("GNW_Bazzar.Entity.Otp", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("GNW_Bazzar.Entity.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Navigation("Otp")
                        .IsRequired();

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
