// <auto-generated />
using System;
using GNW_Bazzar.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GNW_Bazzar.Entity.Migrations
{
    [DbContext(typeof(GNW_BazaarDbContext))]
    partial class GNW_BazaarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryMasters");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Health Care",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8076),
                            Description = "Health Care related services",
                            IsActive = false
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Food",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8087),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Shopping",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8090),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Makeovers",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8092),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Events",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8095),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Travel",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8097),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Homecare",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8099),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Property",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8101),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Astrology",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8104),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Education",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8106),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "FitLife",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8108),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Pets",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8110),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Relocation",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8112),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Finance",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8114),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 15L,
                            CategoryName = "Security",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8116),
                            Description = "",
                            IsActive = false
                        },
                        new
                        {
                            Id = 16L,
                            CategoryName = "Service",
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8118),
                            Description = "",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AboutDoctor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<long>("HealthCareSubCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareSubCategoryId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CategoryMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMasterId");

                    b.ToTable("HealthCareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Anaesthesiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8378)
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Cardiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8382)
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Critical Care",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8385)
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Dentistry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8387)
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Dermatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8390)
                        },
                        new
                        {
                            Id = 6L,
                            Category = "Endocrinology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8392)
                        },
                        new
                        {
                            Id = 7L,
                            Category = "ENT",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8395)
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Gastroenterology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8397)
                        },
                        new
                        {
                            Id = 9L,
                            Category = "General Physician",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8399)
                        },
                        new
                        {
                            Id = 10L,
                            Category = "General Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8401)
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Geriatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8403)
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Gynecology & Obstetrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8405)
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Hematology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8407)
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Hepatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8409)
                        },
                        new
                        {
                            Id = 15L,
                            Category = "Immunology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8411)
                        },
                        new
                        {
                            Id = 16L,
                            Category = "Infectious Diseases",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8413)
                        },
                        new
                        {
                            Id = 17L,
                            Category = "Internal Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8416)
                        },
                        new
                        {
                            Id = 18L,
                            Category = "Interventional Spine & Pain Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8418)
                        },
                        new
                        {
                            Id = 19L,
                            Category = "IVF",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8420)
                        },
                        new
                        {
                            Id = 20L,
                            Category = "Nephrology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8422)
                        },
                        new
                        {
                            Id = 21L,
                            Category = "Neurology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8424)
                        },
                        new
                        {
                            Id = 22L,
                            Category = "Nuclear Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8426)
                        },
                        new
                        {
                            Id = 23L,
                            Category = "Nutrition & Health",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8428)
                        },
                        new
                        {
                            Id = 24L,
                            Category = "Oncology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8429)
                        },
                        new
                        {
                            Id = 25L,
                            Category = "Ophthalmology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8432)
                        },
                        new
                        {
                            Id = 26L,
                            Category = "Orthopedics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8434)
                        },
                        new
                        {
                            Id = 27L,
                            Category = "Pathology & Laboratory Medicine",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8436)
                        },
                        new
                        {
                            Id = 28L,
                            Category = "Pediatrics",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8438)
                        },
                        new
                        {
                            Id = 29L,
                            Category = "Physiotherapy & Rehabilitation",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8440)
                        },
                        new
                        {
                            Id = 30L,
                            Category = "Plastic & Reconstructive Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8442)
                        },
                        new
                        {
                            Id = 31L,
                            Category = "Psychology & Psychiatry",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8444)
                        },
                        new
                        {
                            Id = 32L,
                            Category = "Pulmonology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8446)
                        },
                        new
                        {
                            Id = 33L,
                            Category = "Radiology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8448)
                        },
                        new
                        {
                            Id = 34L,
                            Category = "Rheumatology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            Id = 35L,
                            Category = "Robotic Surgery",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8561)
                        },
                        new
                        {
                            Id = 36L,
                            Category = "Urology",
                            CategoryMasterId = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8563)
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("HealthCareCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HealthCareCategoryId");

                    b.ToTable("HealthCareSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8652),
                            HealthCareCategoryId = 2L,
                            SubCategory = "Heart"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8656),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Hormones"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8658),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Diabetes"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8662),
                            HealthCareCategoryId = 6L,
                            SubCategory = "Thyroid"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8664),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Ear"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8667),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Nose"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8669),
                            HealthCareCategoryId = 7L,
                            SubCategory = "Throat"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8671),
                            HealthCareCategoryId = 8L,
                            SubCategory = "Digestive System"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8673),
                            HealthCareCategoryId = 9L,
                            SubCategory = "Family Medicine"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8675),
                            HealthCareCategoryId = 11L,
                            SubCategory = "Elderly Care"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8677),
                            HealthCareCategoryId = 13L,
                            SubCategory = "Blood"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8679),
                            HealthCareCategoryId = 14L,
                            SubCategory = "Liver"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8682),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Allergies"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8684),
                            HealthCareCategoryId = 15L,
                            SubCategory = "Immune Disorders"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8686),
                            HealthCareCategoryId = 20L,
                            SubCategory = "Kidneys"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8688),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Brain"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8691),
                            HealthCareCategoryId = 21L,
                            SubCategory = "Nervous System"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8693),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8695),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Bone Marrow Transplant"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8697),
                            HealthCareCategoryId = 24L,
                            SubCategory = "Cancer Care"
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8700),
                            HealthCareCategoryId = 25L,
                            SubCategory = "Eye Surgery"
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8702),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Bones"
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8704),
                            HealthCareCategoryId = 26L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8706),
                            HealthCareCategoryId = 32L,
                            SubCategory = "Lungs"
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8708),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Joints"
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8710),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Arthritis"
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8712),
                            HealthCareCategoryId = 34L,
                            SubCategory = "Autoimmune"
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8714),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Urinary Tract"
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2025, 9, 4, 15, 36, 17, 433, DateTimeKind.Utc).AddTicks(8717),
                            HealthCareCategoryId = 36L,
                            SubCategory = "Male Reproductive"
                        });
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Attempts")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Doctor", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareSubCategory", "healthCareSubCategory")
                        .WithMany()
                        .HasForeignKey("HealthCareSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("healthCareSubCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.CategoryMaster", "CategoryMaster")
                        .WithMany("HealthCareCategories")
                        .HasForeignKey("CategoryMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareSubCategory", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.HealthCareCategory", "HealthCareCategory")
                        .WithMany("HealthCareSubCategories")
                        .HasForeignKey("HealthCareCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCareCategory");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.Otp", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("Otp")
                        .HasForeignKey("GNW_Bazzar.Entity.Otp", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.RefreshToken", b =>
                {
                    b.HasOne("GNW_Bazzar.Entity.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("GNW_Bazzar.Entity.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.CategoryMaster", b =>
                {
                    b.Navigation("HealthCareCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.HealthCareCategory", b =>
                {
                    b.Navigation("HealthCareSubCategories");
                });

            modelBuilder.Entity("GNW_Bazzar.Entity.User", b =>
                {
                    b.Navigation("Otp")
                        .IsRequired();

                    b.Navigation("RefreshToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
